name: App CI CD

on:
  workflow_dispatch:
 
  pull_request:
    branches:
      - dev
      - stage
      - production
  push:
    branches:
      - dev
      - stage
      - production

permissions:
  contents: read
  id-token: write

jobs:
  dummy_ping:
    name: dummy-ping
    runs-on: ubuntu-latest
    steps:
      - name: Echo workflow execution
        run: |
          echo "[DUMMY] Workflow is running"
          echo "[DUMMY] Event: ${{ github.event_name }}"
          echo "[DUMMY] Ref: ${{ github.ref }}"

  mandatory_ci:
    name: mandatory-ci
    needs: dummy_ping
    uses: felipecembranelliorg/platform-devops-poc/.github/workflows/dotnet-ci.yml@master
    with:
      dotnet_version: '9.0.x'
      solution_path: './src/MyApp.sln'
      run_tests: true
      build_configuration: 'Release'
      docker_image_name: 'myapp-api'
    secrets: inherit

  deploy_dev:
    name: deploy-dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    needs: mandatory_ci
    uses: felipecembranelliorg/platform-devops-poc/.github/workflows/aks-deploy.yml@master
    with:
      environment_name: DEV
      aks_cluster_name: aks-dev-01
      aks_resource_group: rg-dev-platform
      aks_namespace: myapp-dev
      docker_image_name: myapp-api
      kubernetes_manifest_path: ./k8s/deployment.yaml
    secrets: inherit


  # deploy_stage:
  #   name: deploy-stage
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/stage'
  #   needs: mandatory_ci
  #   uses: felipecembranelliorg/platform-devops-poc/.github/workflows/aks-deploy.yml@v1
  #   with:
  #     environment_name: STG
  #     aks_cluster_name: aks-stage-01
  #     aks_resource_group: rg-stage-platform
  #     aks_namespace: myapp-stage
  #     docker_image_name: myapp-api
  #     kubernetes_manifest_path: ./k8s/deployment.yaml
  #   secrets: inherit

  # deploy_prod:
  #   name: deploy-prod
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/production'
  #   needs: mandatory_ci
  #   uses: felipecembranelliorg/platform-devops-poc/.github/workflows/aks-deploy.yml@v1
  #   with:
  #     environment_name: production
  #     aks_cluster_name: aks-prod-01
  #     aks_resource_group: rg-prod-platform
  #     aks_namespace: myapp-prod
  #     docker_image_name: myapp-api
  #     kubernetes_manifest_path: ./k8s/deployment.yaml
  #   secrets: inherit
